version: "3.9"
services:
  node-red:
    build: 
      context: ./node-red
    networks:
      - node_red
    ports:
      - "1880:1880"
    environment:
      DB_USER: root
      DB_PASS: pass
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: dev      
      FLOWS: "/data/flows.json"

    depends_on:
      - redis_microservice  
      
    volumes:
      - "./node-red/:/data" 

  redis_microservice:
    build:
      context: ./redis_microservice
    networks:
      - node_red
    ports:
      - "6379:6379"
  python_microservice:
    build:
      context: ./python_queue_microservice
    networks:
      - node_red
    depends_on:
      - redis_microservice

networks: 
  node_red:
    name: node_red