version: "3.9"
services:
  node-red:
    build: 
      context: ./node-red
    
    ports:
      - "1880:1880"
    environment:
      FLOWS: "/data/flows.json"

    depends_on:
      - mosquitto  
      
    volumes:
      - "./node-red/:/data" 
    
    networks:
      - demo-stack

  grafana:
    image: grafana/grafana:latest
    ports:
      - '3000:3000'
    volumes:
      - "./grafana:/var/lib/grafana"
    networks:
      - demo-stack

  mosquitto:
    image: eclipse-mosquitto:latest
    ports:
      - '1883:1883'
      - '9001:9001'
    environment:
    - MOSQUITTO_USERNAME=username
    - MOSQUITTO_PASSWORD=password
    
    networks:
      - demo-stack

networks:
  demo-stack:
