version: "3.9"
services:
  node-red:
    build: 
      context: ./node-red
    networks:
      - node_red
    ports:
      - "1880:1880"
    environment:
      FLOWS: "/data/flows.json"

    depends_on:
      - redis_microservice  
      
    volumes:
      - "./node-red/:/data" 

  redis_microservice:
    build:
      context: ./redis_microservice
    networks:
      - node_red

  python_microservice:
    build:
      context: ./python_queue_microservice
    networks:
      - node_red
    depends_on:
      - redis_microservice

  grafana:
    build: ./grafana
    ports:
      - '3000:3000'
    networks:
      - node_red
    volumes:
      - "./grafana:/var/lib/grafana"

networks: 
  node_red:
    name: node_red


